config/routes.rb
Rails.application.routes.draw do
  get "/" => "home#index"

  resources :users

  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
  resources :about
  resources :menus
  resources :menu_items
  resources :orders
  resources :order_items
  get "/pending_orders", to: "orders#pending_orders", as: :pending_orders
  get "/reports", to: "orders#reports", as: :reports
  post "/invoice/:id", to: "orders#invoice", as: :invoice
end

app/models/menuitem.rb
class Menuitem < ActiveRecord::Base
  validates :name, presence: true
  validates :price, presence: true
  validates :category, presence: true

  belongs_to :menu
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  def index
    @categories = Menuitem.distinct.pluck(:category)
    @categories.sort!
    @order = current_user.orders.being_created
    if @order
      @orderitem = @order.orderitems
    end
    render "index"
  end

  def edit
    @menuitem = Menuitem.find(params[:id])
    @categories = Menuitem.distinct.pluck(:category)
  end

  def create
    menu = Menu.active
    menu_item = Menuitem.new(
      menu_id: menu.id,
      name: params[:name],
      description: params[:description],
      price: params[:price],
      category: params[:category],
      imgurl: params[:imgurl],
    )
    if menu_item.save
      flash[:notice] = "New item is created successfully!"
      redirect_to menu_items_path
    else
      flash[:error] = menu_item.errors.full_messages.join(", ")
      redirect_to menu_items_path
    end
  end

  def update
    menu = Menu.active
    menuitem = Menuitem.find(params[:id])
    menuitem.update(
      menu_id: menu.id,
      name: params[:name],
      description: params[:description],
      price: params[:price],
      category: params[:category],
      imgurl: params[:imgurl],
    )
    flash[:notice] = "Item with ID:#{menuitem.id} is updated successfully!"
    redirect_to menu_items_path
  end

  def destroy
    menuitem = Menuitem.find(params[:id])
    menuitem.destroy
    flash[:notice] = "Item with ID:#{menuitem.id} is deleted!"
    redirect_to menu_items_path
  end
end

app/views/menu_items/_menulist.html.erb
<body class="classbody">
<section class="Category-section">
  <p class="Category-title"> <%= category %> </p>
  <br><br>

  <ul>
    <% menu=menus.menuitems.order("id") %>
    <% menu.all.each do |menuitem| %>
      <% if menuitem.category == category %>
        <li class="MenuItem-list">
          <section class="MenuItem-container">
            <p class="MenuItemList-text">
              <span class="MenuItemList-name">
                <%= menuitem.name %>
              </span>
              <span class="MenuItemList-price">
                <%= menuitem.price %> Rs
                <a
                  data-toggle="tooltip"
                  class="btn"
                  animation=true
                  trigger= "click hover focus"
                  title="<%= menuitem.description %>"
                >
                  <%= image_tag "icons8-info-50.png", class: "info-img" %>
                </a>
                <script>
                  $('[data-toggle="tooltip"]').tooltip({
                    template: '<div class="tooltip tooltip-custom"><div class="title">Description</div><div> <%= image_tag "#{menuitem.imgurl}", class: "img1" %> </div><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>'
                  })
                </script>
              </span>
            </p>

            <% if @current_user.role == "Manager" %>
              <%= link_to edit_menu_item_path(id: menuitem.id), method: :get, class: "MenuItem-icon"  do %>
                <%= image_tag "icons8-edit-64.png", class: "icons8-icon" %>
              <% end %>

              <%= link_to "/menu_items/#{menuitem.id}", method: :delete, class: "MenuItem-icon" do %>
                <%= image_tag "icons8-trash-can-64.png", class: "icons8-icon" %>
              <% end %>
            <% end %>

            <% if @order %>
              <% if @orderitem.get(menuitem.id) %>
                <p class="CartqtyUpdate-button">
                  <%= link_to "-  ",
                    "/order_items/#{@orderitem.get(menuitem.id).id}?page=0&symbol=0",
                    method: :patch,
                    class: "CartUpdate-link"
                  %>
                  <%= @orderitem.get_qty(menuitem.id) %>
                  <%= link_to  "  +",
                    "/order_items/#{@orderitem.get(menuitem.id).id}?page=0&symbol=1",
                    method: :patch,
                    class: "CartUpdate-link"
                  %>
                </p>
              <% else %>
                <%= form_with url: order_items_path(menu_item_id: menuitem.id), method: "POST" do |form| %>
                  <%= form.submit "Add To Cart", class: "AddItemCart-button" %>
                <% end %>
              <% end %>
            <% else %>
              <%= form_with url: order_items_path(menu_item_id: menuitem.id), method: "POST" do |form| %>
                <%= form.submit "Add To Cart", class: "AddItemCart-button" %>
              <% end %>
            <% end %>
          </section>
        </li>
      <% end %>
    <% end %>
  </ul>
</section>
</body>

app/views/menu_items/edit.html.erb
<body class="classbody">
<h1 class=EditMenuItemPage-title>Edit Menu Item</h1>

  <section class="MenuItem-section">
    <section class="AddMenuItem">
      <%= form_with url: "/menu_items/#{@menuitem.id}", method: :patch do |form| %>
        <%= form.text_field :name,
          class: "AddMenuItem-text",
          placeholder: "MenuItem Name",
          value: @menuitem.name,
          autofocus: "autofocus"
        %>

        <%= form.text_field :description,
          class: "AddMenuItem-text",
          placeholder: "Description",
          value: @menuitem.description,
          autofocus: "autofocus"
        %>

        <%= form.number_field :price,
          class: "AddMenuItem-price",
          placeholder: 0.0,
          value: @menuitem.price,
          autofocus: "autofocus"
        %>

        <select name="category" class="AddMenuItem-text" placeholder="Category" include_blank=true>
          <option value= "<%= @menuitem.category %>" > <%= @menuitem.category %> </option>
          <% @categories.each do |category| %>
            <option value = "<%= category %>" > <%= category %> </option>
          <% end %>
        </select>

        <%= form.text_field :imgurl,
          class: "AddMenuItem-text",
          placeholder: "image url",
          value: @menuitem.imgurl,
          autofocus: "autofocus"
        %>

        <%= form.submit "Update", class: "AddMenuItem-button" %>
      <% end %>
    </section>
  </section>
</body>

app/views/menu_items/index.html.erb
<body class="classbody">
<% menu = Menu.active %>
<h3 class=MenuItemPage-title> <%= menu.name %> </h3>

<% if @current_user.role == "Manager" %>
  <section class="AddMenuItem">
    <%= form_with url: menu_items_path, method: "POST" do |form| %>
      <%= form.text_field :name, class: "AddMenuItem-text", placeholder: "Any new MenuItem?" %>
      <%= form.text_field :description, class: "AddMenuItem-text", placeholder: "Description" %>
      <%= form.number_field :price, class: "AddMenuItem-price", placeholder: 0.0 %>
      <select name="category" class="AddMenuItem-text" placeholder="Category" include_blank=true>
        <option value="">Select Category</option>
        <% @categories.each do |category| %>
          <option value = "<%= category %>" > <%= category %> </option>
        <% end %>
      </select>
      <%= form.text_field :imgurl, class: "AddMenuItem-text", placeholder: "image url" %>
      <%= form.submit "Add", class: "AddMenuItem-button" %>
    <% end %>
  </section>

  <h2 class="WalkIn-title">Order for Walk-In Customer</h2>
<% end %>

<% @categories.each do |category| %>
  <%= render partial: "menulist", locals: {category: category, menus: menu} %>
<% end %>
</body>