config/routes.rb
Rails.application.routes.draw do
  get "/" => "home#index"

  resources :users

  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
  resources :about
  resources :menus
  resources :menu_items
  resources :orders
  resources :order_items
  get "/pending_orders", to: "orders#pending_orders", as: :pending_orders
  get "/reports", to: "orders#reports", as: :reports
  post "/invoice/:id", to: "orders#invoice", as: :invoice
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :orderitems
  belongs_to :user

  def self.of_user(user)
    all.where(user_id: user.id)
  end

  def self.being_created
    where("status = ?", "being_created").first
  end

  def self.conf_and_del
    where.not("status = ?", "being_created")
  end

  def self.get_pending_orders
    where("status = ?", "order_confirmed")
  end

  def self.is_delivered
    if status == "delivered"
      true
    else
      false
    end
  end

  def status_tostring
    if status == "delivered"
      if delivered_at
        "Delivered on #{delivered_at.strftime("%-d %b,%Y")} at #{delivered_at.strftime("%I:%M %P")}"
      end
    elsif status == "being_created"
      "Being Created"
    else
      "Order Confirmed"
    end
  end

  def totalprice
    price = 0
    orderitems.each { |item| price = price + (item.menu_item_price * item.qty) }
    price
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.where(user_id: current_user.id).conf_and_del.order("id DESC")
    @all_orders = Order.conf_and_del.order("id DESC")
    render "index"
  end

  def new
    @order = @current_user.orders.being_created
    render "new"
  end

  def update
    order = Order.find(params[:id])
    if order.status == "being_created"
      order.status = "order_confirmed"
      order.date = Date.today
      order.save!
      flash[:notice] = "Your order with ID:#{order.id} is confirmed!"
      redirect_to menu_items_path
    else
      order.status = "delivered"
      order.delivered_at = DateTime.now + (5.5 / 24)
      order.save!
      flash[:notice] = "Your order with ID:#{order.id} is delivered!"
      redirect_to pending_orders_path
    end
  end

  def pending_orders
    ensure_not_user
    @orders = Order.get_pending_orders.order("id ASC")
    render "pending_orders"
  end

  def reports
    ensure_manager
    id = params[:id]
    from = Date.parse(params[:from])
    to = Date.parse(params[:to])
    if id.blank?
      @orders = Order.where("delivered_at >= ? AND delivered_at <= ?", from, to)
    elsif from.blank? && to.blank?
      @orders = Order.where("user_id = ?", id)
    elsif id.blank? && from.blank? && to.blank?
      @orders = Order.all
    else
      @orders = Order.where("delivered_at >= ? AND delivered_at <= ? AND user_id = ?", from, to, id)
    end
    render "reports"
  end

  def invoice
    @order = Order.find(params[:id])
    render "invoice"
  end
end

app/views/orders/_orderlist.html.erb
<body class="classbody">
<% if @current_user.role == "Manager" %>
  <% if report_form %>
    <section class="Reports">
      <%= form_with url: reports_path, method: :get, local: true do |form| %>
        <%= form.text_field :id, class: "Reports-text", placeholder: "User Id" %>
        <label class="Reports-label">
          From:
          <%= form.date_field :from, class: "Reports-date" %>
        </label>
        <label class="Reports-label">
          To:
          <%= form.date_field :to, class: "Reports-date" %>
        </label>
        <%= form.submit "Search", class: "Reports-button" %>
      <% end %>
    </section>
  <% end %>
<% end %>

<% orders.each do |order| %>
  <% if order.user %>
    <section class="OrderItem-section">
      <p class="OrderId-text"> Order Id: <%= order.id %> </p>

      <p class="Ordered-by">
        <% if order.user.role == "User" %>
          <%= order.user.first_name %> <%= order.user.last_name %>
        <% else %>
          Walk-In Customer
        <% end %>
      </p>

      <section class="OrderItem-content">
        <ul>
          <% order.orderitems.each do |orderitem| %>
            <% if orderitem.qty > 0 %>
              <li class="Order-text">
                <span> <%= orderitem.menu_item_name %> x <%= orderitem.qty %> </span>
                <p class="total-price">
                  <%= orderitem.menu_item_price*orderitem.qty %> Rs.
                </p>
              </li>
            <% end %>
          <% end %>
        </ul>
      </section>

      <p class="Total-price">Total: <%= order.totalprice %> Rs. </p>

      <section class="Placeorder">
        <% if pending_button %>
          <%= form_with url: "/orders/#{order.id}", method: :patch do |form| %>
            <%= form.submit "Deliver", class: "PlaceOrder-button" %>
          <% end %>
        <% end %>

        <% if invoice_button %>
          <%= form_with url: invoice_path(id: order.id), method: :post, local: true do |form| %>
            <%= form.submit "Invoice", class: "PlaceOrder-button" %>
          <% end %>
        <% end %>
      </section>

      <p class="Order-status"> <%= order.status_tostring %> </p>
    </section>
 <% end %>
<% end %>
</body>

app/views/orders/index.html.erb
<body class="classbody">
<% if @current_user.role == "User" %>
  <h1 class="Order-title">My orders</h1>
  <%= render partial: "orderlist", locals: {
    orders: @orders,
    pending_button: false,
    report_form: false,
    invoice_button: true
  } %>


<% else %>
  <h1 class="Order-title">Orders</h1>
  <%= render partial: "orderlist", locals: {
    orders: @all_orders,
    pending_button: false,
    report_form: true,
    invoice_button: true
  } %>
<% end %>
</body>

app/views/orders/invoice.html.erb
<body class="classbody">
<h1 class="Order-title">Invoice details</h1>

<% if @order.user %>
  <section class="Invoice-section">
    <section class="InvoiceSection-text">
      <p> Order Id: <%= @order.id %> </p>
      <% if @order.delivered_at %>
        <p class="Right-text">
          Delivered date:
          <span class="invoice-date">
            <%= @order.delivered_at.strftime("%-d %b,%Y") %> at <%= @order.delivered_at.strftime("%I:%M %P") %>
          </span>
        </p>
      <% end %>
    </section>
    <br>

    <section class="InvoiceSection-text">
    <% if @order.date %>
      <p> Ordered date:
        <span class="invoice-date">
          <%= @order.date.strftime("%-d %b, %Y") %>
        </span>
      </p>
    <% end %>
    </section>
    <br>

    <section class="InvoiceSection-text">
      <p class="spl-txt"> Billing To: </p>
      <% if @order.user.role == "User" %>
        <% if @order.user.address %>
          <p class="Right-text spl-txt"> Shipping To: </p>
        <% end %>
      <% end %>
    </section>
    <br>

    <section class="InvoiceSection-text">
      <% if @order.user.role == "User" %>
        <p class="User-fullname"> <%= @order.user.first_name %> <%= @order.user.last_name %> </p>
        <% if @order.user.address %>
          <p class="Right-text"> <%= @order.user.address %> </p>
        <% end %>
      <% else %>
        <p>Walk-In Customer</p>
      <% end %>
    </section>
    <br>

    <section class="InvoiceSection-text">
      <% if @order.user.role == "User" %>
        <% if @order.user.phone %>
          <p> <%= @order.user.phone %> </p>
        <% end %>
      <% end %>
    </section>
    <br>

  <section class="Cart-section">
    <p class="Cart-heading">
      <span class="Invoice-item">Item Name</span>
      <span class="Cart-price">Qty</span>
      <span class="Cart-price">Cost</span>
      <span class="Cart-price">Total Cost</span>
    </p>
    <ul>
      <% @order.orderitems.all.each do |orderitem| %>
        <% if orderitem.qty > 0 %>
          <li class="Cart-content">
            <span class="Invoice-item"> <%= orderitem.menu_item_name %> </span>
            <span class="Cart-price">
              <p>
                <%= orderitem.qty %>
              </p>
            </span>
            <span class="Cart-price">
              <p>
                <%= orderitem.menu_item_price %> Rs.
              </p>
            </span>
            <span class="Cart-price">
              <p>
                <%= orderitem.menu_item_price*orderitem.qty %> Rs.
              </p>
            </span>
          </li>
        <% end %>
      <% end %>
    </ul>

    <p class="Total-price">Total: <%= @order.totalprice %> Rs. </p>
  </section>
<% end %>
</body>

app/views/orders/new.html.erb
<body class="classbody">
<% if @current_user.role == "User" %>
  <h1 class="Cart-title">My Cart</h1>
<% else %>
  <h1 class="Cart-title">Offline Cart</h1>
<% end %>

<% if @order == nil || @order.totalprice == 0 %>
  <h6 class="Emptycart-text">Cart is empty!</h6>
<% else %>
  <section class="Cart-section">
    <p class="Cart-heading">
      <span>Item Name</span>
      <span class="Cart-price">Price</span>
    </p>
    <ul>
      <% orders=@order.orderitems.order("id") %>
      <% orders.all.each do |orderitem| %>
        <% if orderitem.qty > 0 %>
          <li class="Cart-content">
            <span> <%= orderitem.menu_item_name %> </span>
            <span class="Cart-price">
              <p class="Cart-update">
                <%= link_to "-  ",
                  "/order_items/#{orderitem.id}?page=1&symbol=0",
                  method: :patch,
                  class: "CartUpdate-link",
                  remote: false
                %>
                <%= orderitem.qty %>
                <%= link_to  "  +",
                  "/order_items/#{orderitem.id}?page=1&symbol=1",
                  method: :patch,
                  class: "CartUpdate-link",
                  remote: false
                %>
              </p>
              <p class="qty-price">
                <%= orderitem.menu_item_price*orderitem.qty %> Rs.
              </p>
            </span>
            <span>
              <%= link_to "/order_items/#{orderitem.id}", method: "DELETE" do %>
                <%= image_tag "icons8-delete-bin-50.png", class: "icons8-icon" %>
              <% end %>
            </span>
          </li>
        <% end %>
      <% end %>
    </ul>

    <p class="Total-price">Total: <%= @order.totalprice %> Rs. </p>

    <section class="Place-order">
      <%= form_with url: "/orders/#{@order.id}", method: "PATCH" do |form| %>
        <%= form.submit "Place Order", class: "PlaceOrder-button" %>
      <% end %>
    </section>
  </section>
<% end %>
<body>

app/views/orders/pending_orders.html.erb
<body class="classbody">
<h1 class="Order-title">Pending Orders</h1>
<% if @orders %>
  <%= render partial: "orderlist", locals: {
    orders: @orders,
    pending_button: true,
    report_form: false,
    invoice_button: false
  } %>
<% else %>
  <h6 class="Emptycart-text">No orders are pending to get delivered!</h6>
<% end %>
</body>

app/views/orders/reports.html.erb
<body class="classbody">
<h1 class="Order-title">Sales Report</h1>
<%= render partial: "orderlist", locals: {
  orders: @orders,
  pending_button: false,
  report_form: false,
  invoice_button: true
  } %>
</body>