config/routes.rb
Rails.application.routes.draw do
  get "/" => "home#index"

  resources :users

  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
  resources :about
  resources :menus
  resources :menu_items
  resources :orders
  resources :order_items
  get "/pending_orders", to: "orders#pending_orders", as: :pending_orders
  get "/reports", to: "orders#reports", as: :reports
  post "/invoice/:id", to: "orders#invoice", as: :invoice
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cafeteria Manager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1" />

    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Andika" />
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Lato" />
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=B612" />
  </head>

  <body>
    <% if @current_user %>
      <nav class="navbar navbar-expand-md bg-dark navbar-dark">
        <a href="#" class="pull-left">
          <%= image_tag "icons8-school-cafeteria-50-2.png", class: "nav-icon" %>
        </a>
        <%= link_to "Cafeteria Management",
          about_index_path,
          class: "navbar-brand",
          style: "margin-right: 50px"
        %>

        <section class="nav-links">
          <button
            class="navbar-toggler pos"
            type="button"
            data-toggle="collapse"
            data-target="#collapsibleNavbar"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="div-class">
            <br><br><br>
          </div>
          <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav nav-links">
              <li class="nav-item nav-items">
                <%= image_tag "icons8-about-48.png", class: "nav-icons" %>
                <%= link_to "About Us", about_index_path, class: "nav-link" %>
              </li>

              <% if @current_user.role == "Manager" %>
                <li class="dropdown nav-link nav-item nav-items">
                  <a class="dropdown-toggle" data-toggle="dropdown">
                    <%= image_tag "icons8-restaurant-menu-48.png", class: "nav-icons" %>
                    Menus
                  </a>
                  <ul class="dropdown-menu bg-dark">
                    <li class="nav-item nav-items">
                      <%= image_tag "icons8-top-menu-64.png", class: "nav-icons" %>
                      <% if @current_user.role == "Manager" %>
                        <%= link_to "ActiveMenu", menus_path, class: "nav-link" %>
                      <% end %>
                    </li>

                    <li class="nav-item nav-items">
                      <%= image_tag "icons8-restaurant-menu-64.png", class: "nav-icons" %>
                      <%= link_to "Menus", menu_items_path, class: "nav-link" %>
                    </li>
                  </ul>
                </li>
              <% else %>
                <li class="nav-item nav-items">
                  <%= image_tag "icons8-restaurant-menu-48.png", class: "nav-icons" %>
                  <%= link_to "Menus", menu_items_path, class: "nav-link" %>
                </li>
              <% end %>


              <% if @current_user.role == "User" %>
                <li class="nav-item nav-items">
                  <%= image_tag "icons8-shopping-bag-64.png", class: "nav-icons" %>
                  <%= link_to "My Orders", orders_path, class: "nav-link" %>
                </li>
              <% else %>
                <li class="dropdown nav-link nav-item nav-items">
                  <a class="dropdown-toggle" data-toggle="dropdown">
                    <%= image_tag "icons8-shopping-bag-64.png", class: "nav-icons" %>
                    Orders
                    <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu bg-dark">
                    <li class="nav-item nav-items">
                      <%= image_tag "icons8-historical-40.png", class: "nav-icons" %>
                      <% unless @current_user.role == "User"  %>
                        <%= link_to "Pending", pending_orders_path, class: "nav-link" %>
                      <% end %>
                    </li>

                    <li class="nav-item nav-items">
                      <%= image_tag "icons8-purchase-order-144.png", class: "nav-icons" %>
                      <%= link_to "All Orders", orders_path, class: "nav-link" %>
                    </li>
                  </ul>
                </li>
              <% end %>

              <li class="nav-item nav-items">
                <%= image_tag "icons8-shopping-cart-48.png", class: "nav-icons" %>
                <% if @current_user.role == "User" %>
                  <%= link_to "My Cart", new_order_path, class: "nav-link" %>
                <% else %>
                  <%= link_to "Offline Cart", new_order_path, class: "nav-link" %>
                <% end %>
              </li>

              <li class="dropdown nav-link nav-item nav-items">
                <a class="dropdown-toggle" data-toggle="dropdown">
                  <span class="name-icon"> <%= @current_user.first_name[0] %> </span>
                  <%= @current_user.first_name %> <%= @current_user.last_name %>
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu bg-dark">
                  <li class="nav-item nav-items">
                    <% if @current_user.role == "Manager" %>
                      <%= image_tag "icons8-team-48.png", class: "nav-icons" %>
                      <%= link_to "Users List", users_path, class: "nav-link" %>
                    <% end %>
                  </li>

                  <li class="nav-item nav-items">
                    <%= image_tag "icons8-edit-48.png", class: "nav-icons" %>
                    <%= link_to "Edit-Profile", edit_user_path(id: @current_user.id), method: :get, local: true, class: "nav-link" %>
                  </li>

                  <li class="nav-item nav-items">
                    <%= image_tag "icons8-sign-out-100.png", class: "nav-icons" %>
                    <%= link_to "Sign-Out", destroy_session_path, method: :delete, class: "nav-link" %>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </section>
      </nav>

      <div class="fixed-nav">
        <%= image_tag "icons8-buying-64.png", class: "nav-icons1" %>
        <%= link_to "View Cart", new_order_path, class: "fixed-link" %>
      </div>

    <% else %>
      <nav class="navbar navbar-expand-md bg-dark navbar-dark">
        <a href="#" class="pull-left">
          <%= image_tag "icons8-school-cafeteria-50-2.png", class: "nav-icon" %>
        </a>
        <%= link_to "Cafeteria Management",
          about_index_path,
          class: "navbar-brand",
          style: "margin-right: 50px"
        %>

        <section class="nav-links">
          <button
            class="navbar-toggler pos"
            type="button"
            data-toggle="collapse"
            data-target="#collapsibleNavbar"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="div-class">
            <br><br><br>
          </div>
          <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav nav-links">
              <li class="nav-item nav-items">
                <%= image_tag "icons8-login-rounded-50-2.png", class: "nav-icons" %>
                <%= link_to "Sign-in", new_sessions_path, class: "nav-link" %>
              </li>

              <li class="nav-item nav-items">
                <%= image_tag "icons8-add-user-male-50.png", class: "nav-icons" %>
                <%= link_to "Sign-Up", new_user_path, class: "nav-link" %>
              </li>
            </ul>
          </div>
        </section>
      </nav>
    <% end %>


    <% if flash[:error] %>
      <p class="Flash-error">
        <%= flash[:error] %>
      </p>
    <% end %>

    <% if flash[:notice] %>
      <p class="Flash-notice">
        <%= flash[:notice] %>
      </p>
    <% end %>

    <%= yield %>
  </body>
</html>